[project]
name = "manifest_parser"
version = "0.1.0"
dependencies = ["colorlog", "jsonschema"]

[project.scripts]
manifest-parser = "manifest_parser.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
