# auth-binding-rs/manifest.yml resources
auth-binding-rs-manifest: auth-binding-rs {
  shape: package
  main: "" {
    shape: hexagon
    caption: |md
      Target: **main**
    |
  }
  auth-binding-rs-binding: "" {
    shape: page
    caption: |md
      name: **auth-binding-rs**<br/>
      value: `lib/libafb_auth.so`
    |
  }
}

# auth-binding-rs/manifest.yml links

# evse-auth-manager-binder/manifest.yml resources
auth-manager-manifest: auth-manager {
  shape: package
  main: "" {
    shape: hexagon
    caption: |md
      Target: **main**
    |
    auth-api: auth {
      shape: circle
    }
    ocpp-api: ocpp {
      shape: circle
    }
  }
}

# evse-auth-manager-binder/manifest.yml links
auth-manager-manifest.main -> auth-binding-rs-manifest.auth-binding-rs-binding: requires
auth-manager-manifest.main -> scard-binding-rs-binding: requires
auth-manager-manifest.main -> ocpp-binding-rs-binding: requires
auth-manager-manifest.main -> energy-manager-manifest.main.engy-api: requires

# evse-energy-manager-binder/manifest.yml resources
energy-manager-manifest: energy-manager {
  shape: package
  main: "" {
    shape: hexagon
    caption: |md
      Target: **main**
    |
    engy-api: engy {
      shape: circle
    }
  }
}

# evse-energy-manager-binder/manifest.yml links
energy-manager-manifest.main -> modbus-binding-binding: requires
energy-manager-manifest.main -> energy-binding-rs-binding: requires

# resources defined elsewhere
scard-binding-rs-binding: |md
  - name: **scard-binding-rs**
  - value: `smth`
|
ocpp-binding-rs-binding: |md
  - name: **ocpp-binding-rs**
  - value: `smth`
|
energy-binding-rs-binding: |md
  - name: **energy-binding-rs**
  - value: `smth`
|
modbus-binding-binding: |md
  - name: **modbus-binding**
  - value: `smth`
|
