@startuml sample

'auth-binding-rs/manifest.yml declared resources
package auth-binding-rs as auth_binding_rs_manifest {
    artifact auth_binding_rs_binding [
        name = **auth-binding-rs**
        value = ""lib/libafb_auth.so""
    ]
}

'evse-auth-manager-binder/manifest.yml declared resources
package auth-manager as auth_manager_manifest {
    component "Target: main" as auth_manager_manifest.main {
        () auth as auth_api
        () ocpp as ocpp_api
    }
}

'evse-energy-manager-binder/manifest.yml declared resources
package energy-manager as energy_manager_manifest {
    component "Target: main" as energy_manager_manifest.main {
        () engy as engy_api
    }
}

'd'autres manifests pas traités ici
artifact scard_binding_rs_binding [
    name = **scard-binding-rs**
    value = ""some path""
]
artifact ocpp_binding_rs_binding [
    name = **ocpp-binding-rs**
    value = ""some path""
]
artifact modbus_binding_binding [
    name = **modbus-binding**
    value = ""some path""
]
artifact energy_binding_rs_binding [
    name = **energy-binding-rs**
    value = ""some path""
]


'auth-binding-rs/manifest.yml links

'evse-auth-manager-binder/manifest.yml links
auth_manager_manifest.main --> auth_binding_rs_binding : requires
auth_manager_manifest.main --> scard_binding_rs_binding : requires
auth_manager_manifest.main --> ocpp_binding_rs_binding : requires
auth_manager_manifest.main --> engy_api : requires

'evse-energy-manager-binder/manifest.yml links
energy_manager_manifest.main --> modbus_binding_binding : requires
energy_manager_manifest.main --> energy_binding_rs_binding : requires

@enduml
